executables:
  - name: mavlink
    args:
      options:
        --registry-uri tcp://localhost:4020
  - name: mavlink-mission
    args:
      options:
        --registry-uri tcp://localhost:4020
  - name: gz
    args:
      options:
        --registry-uri tcp://localhost:4020
  - name: rerun
    args:
      flags:
        --debug

