executables:
  - name: mavlink
    args:
      options:
        --registry-uri tcp://localhost:4020
  - name: mavlink-mission
    args:
      options:
        --registry-uri tcp://localhost:4020
  - name: gz
    args:
      options:
        --registry-uri tcp://localhost:4020
  # - name: planner
  #   args:
  #     flags:
  #       - --publish-octree
  #     options:
  #       --max-distance: 7.5
  # - name: controller
  #   args:
  #     flags:
  #       - --debug
  - name: rerun
