executables:
  - name: mavlink
  - name: mavlink-mission
  - name: zed
    args:
      flags:
        - --map
        - --debug
      options:
        --host: 127.0.0.1
  - name: rerun
    args:
      flags:
        - --map-compression
